return {
  defaults = { lazy = true },

  ui = {
    icons = {
      ft = "ft | ",
      lazy = "Lazy | ",
      loaded = "loaded | ",
      not_loaded = "Not loaded | ",
      cmd = "",
      config = "",
      event = "",
      favorite = "",
      init = "",
      import = "",
      keys = "",
      plugin = "",
      runtime = "",
      require = "",
      source = "",
      start = "",
      task = "",
    },
  },

  performance = {
    rtp = {
      disabled_plugins = {
        "2html_plugin",
        "tohtml",
        "getscript",
        "getscriptPlugin",
        "gzip",
        { "netrw", "netrwPlugin", "netrwSettings", cmd = "Ex" },
        "logipat",
        "matchit",
        "tar",
        "tarPlugin",
        "rrhelper",
        "spellfile_plugin",
        "vimball",
        "vimballPlugin",
        "zip",
        "zipPlugin",
        "tutor",
        "rplugin",
        "syntax",
        "synmenu",
        "optwin",
        "compiler",
        "bugreport",
        "ftplugin",
      },
    },
  },
}
